In [1]:
import numpy as np

In [4]:
list1 = [1,2,3,4,5,6] # creating a list 
list1

[1, 2, 3, 4, 5, 6]

In [7]:
arr1 = np.array(list1) # numpy array 
type(arr1)

numpy.ndarray

In [12]:
arr1[0] # use square brackets to slice arrays
        # python is 'zero-base'

arr1[0:2] # slice from the first to the third entries

array([1, 2])

In [13]:
# can pass in number that is larger than the array size when slicing 
arr1[0:1000]

array([1, 2, 3, 4, 5, 6])

In [25]:
# methods/functions 
print('max : ' + str(arr1.max()))
print('square_root : ' + str(np.sqrt(arr1)))

max : 6
square_root : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [26]:
arr1.shape

(6,)

In [42]:
arr1.reshape(6,1) # change the shape of the array 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [46]:
new_array = np.array([1,2,1,2]).reshape(2,2)
new_array

array([[1, 2],
       [1, 2]])

In [48]:
new_array.transpose()

array([[1, 1],
       [2, 2]])

In [51]:
# we can also reshape the array like this

new_arr = np.array([[1,2],[1,2]])
new_arr

array([[1, 2],
       [1, 2]])

In [56]:
# sum along x-axis
new_array.sum(axis = 1)

array([3, 3])

In [64]:
# create an array with all zeros /ones
zero = np.zeros((10,10))
one = np.ones((10,10))
# random numbers
np.random.randint(0,10,[2,2])

array([[6, 7],
       [8, 6]])

In [65]:
# other random functions
np.random.randn(10) # normal distribution

array([-0.01354831,  0.5071122 ,  0.56723295,  3.09463518, -0.19471571,
        0.72054954,  0.48815556,  0.94755157, -0.21959543, -0.55627439])

In [67]:
# copy function
np.copy(zero)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [74]:
# boolean values
arr_5 = np.array([1,2,3,4,5,6,7,8])
arr_5 >= 6

array([False, False, False, False, False,  True,  True,  True])

In [75]:
import pandas as pd

In [81]:
# create a series
city_list = ['NYC','LA','Chicago','Houston','Phoenix']
population = np.array([8.3,3.9,2.7,2.3,1.6])
ser1 = pd.Series( data = population, index = city_list)

In [93]:
ser1.iloc[-1]
ser1['NYC']

8.3

In [126]:
# add an extra roll to an existing series
ser2 = pd.Series(data=[1.4],index=['SD'])

combined_ser = ser1.append(ser2)
combined_ser

NYC        8.3
LA         3.9
Chicago    2.7
Houston    2.3
Phoenix    1.6
SD         1.4
dtype: float64

In [127]:
ser1.sort_values(ascending = True)

Phoenix    1.6
Houston    2.3
Chicago    2.7
LA         3.9
NYC        8.3
dtype: float64

In [128]:
pd.concat([ser1,ser2])

NYC        8.3
LA         3.9
Chicago    2.7
Houston    2.3
Phoenix    1.6
SD         1.4
dtype: float64

In [129]:
# create a dataframe
df1 = pd.DataFrame(combined_ser,columns=['Population'])
df1

Population
NYC             8.3
LA              3.9
Chicago         2.7
Houston         2.3
Phoenix         1.6
SD              1.4

In [167]:
# add a new column 
city_list_2 = ['NYC','LA','Chicago','Houston','Phoenix','SD']
arr6 = np.array([301,468,227,637,517,301])
series_6 = pd.Series(data=arr6,index = city_list_2)
df2 = pd.DataFrame(series_6,columns=['Area'])
df2

Area
NYC       301
LA        468
Chicago   227
Houston   637
Phoenix   517
SD        301

In [169]:
series_7 = pd.concat([df1,df2],axis = 1)
series_7

Population  Area
NYC             8.3   301
LA              3.9   468
Chicago         2.7   227
Houston         2.3   637
Phoenix         1.6   517
SD              1.4   301